Api implementation
Touchstack/Papertown pull request #197
Opened 2024-08-10 10:43 UTC by borteye

2024-08-10 13:52 UTC, touchstack-technologies requested changes

2024-08-10 13:52 UTC, touchstack-technologies commented on src/Component/PressClubModal/PressClubModal.jsx
> +              type="role"
Please check this input type. Never heard of it. Please correct @borteye

2024-08-10 13:55 UTC, ayequill requested changes

2024-08-10 13:55 UTC, ayequill commented on src/Component/PressClubModal/PressClubModal.jsx
> +              type="role"
Please check this input type. Never heard of it. Please correct @borteye

2024-08-10 15:12 UTC, borteye commented on src/Component/PressClubModal/PressClubModal.jsx
> +              type="role"
done please

2024-08-11 11:36 UTC, ayequill approved these changes

2024-08-11 12:14 UTC, merged